Feat/assignment 10 (#59)
* Commit for demo by changing v1 to v3

diff --git a/.github/workflows/main-push.yml b/.github/workflows/main-push.yml
--- a/.github/workflows/main-push.yml
+++ b/.github/workflows/main-push.yml
@@ -99,6 +99,9 @@ jobs:
               elif [ "$refresh_status" == "Cancelled" ]; then
                 echo "Instance refresh Cancelled."
                 exit 1
+              elif [ "$refresh_status" == "Failed" ]; then
+                echo "Instance refresh Failed."
+                exit 1
               else
                 echo "Instance refresh in progress..."
                 sleep 30
